version: '3.8'

services:
  api:
    build: ./api
    command: rails server -b 0.0.0.0
    container_name: score-backend
    volumes:
      - ./api:/api
    ports:
      - '8000:3000'

  app:
    build: ./app
    command: yarn start
    container_name: score-frontend
    volumes:
      - ./app:/app
      - /app/node_modules
    stdin_open: true
    ports:
      - '3000:3000'
